### ISSUE TITLE
Typo in Swagger.Yaml

### ISSUE THREAD

**Issue by Alexhuszagh** [nemtech/nem2-docs#134]
**Describe the error**

`swagger.yaml` fails to validate using an OpenAPI validator due to a minor type.

**To Reproduce**

Install `pyyaml and bravado-core` with pip. Then, run the following code snippet:

```python
import yaml
from bravado_core.spec import Spec

with open('swagger.yaml') as f:
    raw_spec = yaml.load(f, Loader=yaml.Loader)
spec = Spec.from_dict(raw_spec, config={'use_models': False})
```

**Expected behavior**

The spec should load, however, due to a minor typo, it fails to. The following diff fixes the bug:

```diff
diff --git a/source/resources/collections/swagger.yaml b/source/resources/collections/swagger.yaml
index 2113133b..80d3d9f0 100644
--- a/source/resources/collections/swagger.yaml
+++ b/source/resources/collections/swagger.yaml
@@ -1260,7 +1260,7 @@ definitions:
     type: object
     required:
     - owner
-    - ownerAddres
+    - ownerAddress
     - startHeight
     - endHeight
     - depth
```

**Comment by dgarcia360** [comment]
Thanks, @Alexhuszagh for reporting the issue! The change will be merged with the next release.
