### ISSUE TITLE
Monitoring transaction using websockets

### ISSUE THREAD

**Issue by erikcartman** [nemtech/nem2-docs#135]
Hi.
I am trying to use this example to listen to transaction events.
https://github.com/nemtech/nem2-docs/blob/master/source/resources/examples/typescript/transaction/MonitoringTransactionStatus.ts

And i am facing this error.
`  url: 'http://hugealice.nem.ninja:3000/ws',
     _req: null },
  type: 'error',
  message: 'connect ECONNREFUSED 88.99.192.82:3000',
  error:
   { Error: connect ECONNREFUSED 88.99.192.82:3000`
The only idea i have that this is a problem with url, can you please provide example how valid url is constructed.

**Comment by jontey** [comment]
Hi! It looks like you are trying to connect to a NIS1 node. Unfortunately the nem2-sdk only supports the newer version (NEM-Catapult) nodes. You can connect to the public testnet for Catapult here http://40.90.163.184:3000/

You also can go here http://40.90.163.184:8000/#/node/ for a list of nodes you can connect to

**Comment by erikcartman** [comment]
Thanks a lot for clarification.
