### ISSUE TITLE
files.lock to be deleted

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-docs#16]
It would be nice to mention that files.lock have to be deleted before running `docker-compose up` in the folders:
-data/api-node-0
-data/peer-node-0
-data/peer-node-1

in order to avoid the following error that prevents publishing transctions:
peer-node-1_1             | 2018-09-09 05:02:33.663364 0x00007ff29d98e740: <warning> (io::FileLock.cpp@74) LockOpen failed: 2 
peer-node-1_1             | 2018-09-09 05:02:33.663546 0x00007ff29d98e740: <fatal> (server::ServerMain.cpp@91) could not acquire instance lock "/data/file.lock" 

This error has also been mentionned [on the NEM forum,](https://forum.nem.io/t/getting-error-api-node-0-1-exited-with-code-253/17471) but the answer is not very clear

**Comment by dgarcia360** [comment]
Should be solved in https://github.com/tech-bureau/catapult-service-bootstrap

**Comment by decentraliser** [comment]
I haven't tried yet

**Comment by dgarcia360** [comment]
Should have been solved with the latest catapult-service-bootstrap update, as the chain can be restarted.
