### ISSUE TITLE
Namespace name allowed characters should not have the apostrophe.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/nem2-docs#172]
In the Namespace page(https://nemtech.github.io/concepts/namespace.html), in the name description where allowed characters were listed, the apostrophe(') should be removed.

A namespace name must be unique and may have a maximum length of 64characters. Allowed characters are a, b, c, …, z, 0, 1, 2, …, 9, ‘, _ , -.

**Comment by dgarcia360** [comment]
@Wayonb Thanks for reporting! It has already been fixed for the next release.
