### ISSUE TITLE
Swagger Doc AccountIds does not meet rest requirement

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-docs#231]
**Describe the error**
Some catapult-rest endpoints expect `oneOf` the properties from request body. E.g. the `accountNames` endpoint. 
either 
```
{ "addresses": ["....."] } 
```
or 
```
{"publicKeys":["....."]}
```

However, the generated Dto model creates 2 keys with one undefined
```
{    
     publicKeys: undefined,
     addresses: [ 'SAMA2UEQNAQ45DWYDNJVLPWKQJDAHFZIVLWACIGN' ] 
} 
```

**To Reproduce**
Use generated http client call `account/names` endpoint

**Expected behavior**
DTO model should match rest server requirements

**Screenshots**

**Additional context**
Should either use `oneOf` concept in the doc or create multiple endpoints with each individual property

**Comment by dgarcia360** [comment]
Looking at this. @rg911 Do you recall which endpoints are not accepting both representations?
