### ISSUE TITLE
Fix WARNING: logo file 'logo-nem.svg' does not exist

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-docs#24]
**Error description**
When the documentation is built, the terminal raises the following warning:

    WARNING: logo file 'logo-nem.svg' does not exist

**Steps to reproduce the error:**

1. Clone the repository and  install requirements using pip:

` pip install -r requirements.txt`

2. Build the docs.

` make html`

**Comment by 44uk** [comment]
It is annoying me every time when building the docs.
Please check my PR
=> [Fix Warning "logo file 'logo\-nem\.svg' does not exist" by 44uk · Pull Request \#28 · nemtech/nem2\-docs](https://github.com/nemtech/nem2-docs/pull/28)

**Comment by dgarcia360** [comment]
Appreciate it! Pull request merged 👍
