### ISSUE TITLE
NIS mainnet node error | sorry to bother you,but I really need your help...

### ISSUE THREAD

**Issue by harryweiyongjie** [nemtech/nem2-docs#291]
last day,I run the mainnet NIS node,and it sync the chain height.but today I check the height ,it not increase yet, means it can’t catch up the chain height.I check the output ,there are just some WARNNING.like this:
2019-11-06 01:36:50.633 WARNING forcibly aborting request to http://108.61.168.86:7890/chain/height (org.nem.core.connect.HttpMethodClient lambda$sendRequest$2)
2019-11-06 01:36:50.633 WARNING forcibly aborting request to http://62.75.251.134:7890/chain/height (org.nem.core.connect.HttpMethodClient lambda$sendRequest$2)

then I check the status,it returns 7,4
curl http://127.0.0.1:7890/status
{“code”:7,“type”:4,“message”:“status”}

how can I solve this problem? please help me…

**Comment by Vektrat** [comment]
you are lately asking for a lot of issues here and this is not a general support forum, what you are asking about now is not relevant to this project

if you need community support i suggest you head to the Slack channel and ask there, there's a #help channel 
https://join.slack.com/t/nem2/shared_invite/enQtMzY4MDc2NTg0ODgyLWZmZWRiMjViYTVhZjEzOTA0MzUyMTA1NTA5OWQ0MWUzNTA4NjM5OTJhOGViOTBhNjkxYWVhMWRiZDRkOTE0YmU
