### ISSUE TITLE
Add internationalization

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-docs#30]
Enable docs in different languages.

http://www.sphinx-doc.org/en/master/intl.html

**Pending Tasks:**
- ✔️ Enable i18n  (see [i18n branch](https://github.com/nemtech/nem2-docs/commit/1297b489efd4) inspired in @44uk translation)
- ✔️Add a selector in the navbar or footer to change the language.
- Add .po files for each language in ``locale`` folder. @44uk has started the Japanese docs, see if contributors want to do pull-requests and add .po files to the official repository.
- ✔️Edit Travis CI to upload all the docs in the same gh-pages.
- ✔️Publish a guideline to create and maintain translations.

**Comment by dgarcia360** [comment]
Added selector in the footer to change the language.

![image](https://user-images.githubusercontent.com/9107969/46468038-47186300-c7c7-11e8-951e-40dafadef30e.png)

**Comment by dgarcia360** [comment]
Edited Travis CI to upload all the docs in the same gh-pages.

**Comment by dgarcia360** [comment]
@44uk Could you make a pull-requests with [locale](https://github.com/44uk/nem2-docs/tree/ja/source/locale) to i18n branch to merge the Japanese translation?

**Comment by dgarcia360** [comment]
[Published a guideline](https://github.com/nemtech/nem2-docs/commit/36557299cd0c2dab0d6ebf7043fa820a31cf8b18#diff-e63ddafba09983226d43c2b198ebebbc) to create and maintain translations.

**Comment by 44uk** [comment]
Thank you!✌️ I prepare to create MR. Please wait a moment.

**Comment by 44uk** [comment]
@dgarcia360 Sorry for my late reply. I pushed translation files. Please update i18n branch. These files are based on latest commit(https://github.com/nemtech/nem2-docs/commit/bc586d0d699ceff19b311c0b2f3ede2b5fc91d0d)
https://github.com/nemtech/nem2-docs/pull/33
