### ISSUE TITLE
Sample codes to create a mosaic does not work (TypeScript, JavaScript)

### ISSUE THREAD

**Issue by gologo13** [nemtech/nem2-docs#316]
**Describe the error**

Hi, I followed the following tutorial to create a mosaic and executed the JS and TS samples, but neither worked for me.

https://nemtech.github.io/guides/mosaic/creating-a-mosaic.html

network type is `MIJIN_TEST`.
I thought there was something wrong with my catapult server at first, but it wasn't.
I could create a mosaic with nem2-desktop-wallet, connecting to the local node.

I compared the source code I used and one of nem2-desktop-wallet.
https://github.com/nemfoundation/nem2-desktop-wallet/blob/cc56735f1ee78576856ff3d493efc9a22cfbeb71/src/components/forms/mosaic-creation/MosaicCreationTs.ts

AFAIS, these is no significant difference to me...
Am I missing something? thanks in advance.

**To Reproduce**

1. Download the sample code (let say JavaScript) from https://nemtech.github.io/guides/mosaic/creating-a-mosaic.html
2. replaced `networkType`, `privateKey`, `networkGenerationHash` and `nodeUrl` values with my own ones
3. run `$ node CreatingAMosaic.js` on terminal
4. the output `TransactionAnnounceResponse {
  message: 'packet 9 was pushed to the network via /transaction' }`

I cannot see any error. the output itself looks normal.

**Expected behavior**

A new mosaic should be created.
Then, a new mosaic entry should be added in a response of the following API:

http://<CATAPULT_SERVER_URL>/account/<OWNER_PUBLIC_KEY>/mosaics

I would appreciate if there is another way to debug my problem.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version: 10.15.2

**Additional context**

none

**Comment by dgarcia360** [comment]
Hi @gologo13, I just executed the code and seems to be working as expected.

`TransactionAnnounceResponse { message: 'packet 9 was pushed to the network via /transaction' }
` means that the transaction has reached the network, but not necessarily that was accepted (e.g. you might have used an incorrect network type, didn't have enough network currency units in your account, used an unexpected networkGenerationHash... ).

To debug the problem, you could add a ``console.log(signedTransaction.hash);`` just after the transaction is signed and run ``node CreatingAMosaic.js``. Then, open the URL ``http://localhost:3000/transaction/<hash>/status`` and you see there why this transaction is not being processed.

**Comment by gologo13** [comment]
Hi @dgarcia360 thank you for your kind response. 
you're right. I got the following response from `/transaction/<hash>/status`:

```
{
hash: "5F63DB18CA4E07F43B30EABCB0657F8C42043AFEFC28B77302408863A614C63D",
code: "Failure_Core_Future_Deadline",
deadline: "118871889910",
group: "failed"
}
```

Looks like there's something wrong with system clocks in my environment.
sorry to bother you. I close this issue.
