### ISSUE TITLE
i can't create namespace and mosaic with multisig

### ISSUE THREAD

**Issue by ags-21ct** [nemtech/nem2-docs#35]
i can't create namespace and monasic with multisig

this code create namespace:
`
const nem2Sdk = require("nem2-sdk");
const operators = require('rxjs/operators');
require('dotenv').load();
    const Address = nem2Sdk.Address,
        Deadline = nem2Sdk.Deadline,
        Account = nem2Sdk.Account,
        UInt64 = nem2Sdk.UInt64,
        NetworkType = nem2Sdk.NetworkType,
        PlainMessage = nem2Sdk.PlainMessage,
        TransferTransaction = nem2Sdk.TransferTransaction,
        Mosaic = nem2Sdk.Mosaic,
        MosaicId = nem2Sdk.MosaicId,
        TransactionHttp = nem2Sdk.TransactionHttp,
        PublicAccount = nem2Sdk.PublicAccount,
        ModifyMultisigAccountTransaction = nem2Sdk.ModifyMultisigAccountTransaction,
        MultisigCosignatoryModification = nem2Sdk.MultisigCosignatoryModification,
        MultisigCosignatoryModificationType = nem2Sdk.MultisigCosignatoryModificationType,
        AccountHttp = nem2Sdk.AccountHttp,
        MosaicDefinitionTransaction = nem2Sdk.MosaicDefinitionTransaction,
        MosaicSupplyChangeTransaction = nem2Sdk.MosaicSupplyChangeTransaction,
        MosaicProperties = nem2Sdk.MosaicProperties,
        MosaicSupplyType = nem2Sdk.MosaicSupplyType,
        XEM = nem2Sdk.XEM,
        AggregateTransaction = nem2Sdk.AggregateTransaction,
        LockFundsTransaction = nem2Sdk.LockFundsTransaction,
        Listener = nem2Sdk.Listener,
        RegisterNamespaceTransaction = nem2Sdk.RegisterNamespaceTransaction,
        filter = operators.filter,
        mergeMap = operators.mergeMap;

        // 01 - Set up
        const transactionHttp = new TransactionHttp( 'http://localhost:3000');

        const cosignatoryPrivateKey = process.env.COSIGNATORY_1_PRIVATE_KEY;
        const cosignatoryAccount = Account.createFromPrivateKey(cosignatoryPrivateKey, NetworkType.MIJIN_TEST);

        const multisigAccountPublicKey = '8AD114F8B5E15D6E3D6101E4690677498B83759FE9A1D001529508F5EB4D46D6';
        const multisigAccount = PublicAccount.createFromPublicKey(multisigAccountPublicKey, NetworkType.MIJIN_TEST);

const namespaceName = "prachakij"; //Replace with an unique namespace name

const registerNamespaceTransaction = RegisterNamespaceTransaction.createRootNamespace(
    Deadline.create(),
    namespaceName,
    UInt64.fromUint(1000),
    NetworkType.MIJIN_TEST);

const signedTransaction = cosignatoryAccount.sign(registerNamespaceTransaction);

transactionHttp
    .announce(signedTransaction)
    .subscribe(x => console.log(x), err => console.error(err));
`

========================

this code create mosaic:

`const nem2Sdk = require("nem2-sdk");
const operators = require('rxjs/operators');
require('dotenv').load();

const Address = nem2Sdk.Address,
    Deadline = nem2Sdk.Deadline,
    Account = nem2Sdk.Account,
    UInt64 = nem2Sdk.UInt64,
    NetworkType = nem2Sdk.NetworkType,
    PlainMessage = nem2Sdk.PlainMessage,
    TransferTransaction = nem2Sdk.TransferTransaction,
    Mosaic = nem2Sdk.Mosaic,
    MosaicId = nem2Sdk.MosaicId,
    TransactionHttp = nem2Sdk.TransactionHttp,
    PublicAccount = nem2Sdk.PublicAccount,
    ModifyMultisigAccountTransaction = nem2Sdk.ModifyMultisigAccountTransaction,
    MultisigCosignatoryModification = nem2Sdk.MultisigCosignatoryModification,
    MultisigCosignatoryModificationType = nem2Sdk.MultisigCosignatoryModificationType,
    AccountHttp = nem2Sdk.AccountHttp,
    MosaicDefinitionTransaction = nem2Sdk.MosaicDefinitionTransaction,
    MosaicSupplyChangeTransaction = nem2Sdk.MosaicSupplyChangeTransaction,
    MosaicProperties = nem2Sdk.MosaicProperties,
    MosaicSupplyType = nem2Sdk.MosaicSupplyType,
    XEM = nem2Sdk.XEM,
    AggregateTransaction = nem2Sdk.AggregateTransaction,
    LockFundsTransaction = nem2Sdk.LockFundsTransaction,
    Listener = nem2Sdk.Listener,
    filter = operators.filter,
    mergeMap = operators.mergeMap;

    // 01 - Set up
    const transactionHttp = new TransactionHttp( 'http://localhost:3000');

    const cosignatoryPrivateKey = process.env.COSIGNATORY_1_PRIVATE_KEY;
    const cosignatoryAccount = Account.createFromPrivateKey(cosignatoryPrivateKey, NetworkType.MIJIN_TEST);

    const multisigAccountPublicKey = '8AD114F8B5E15D6E3D6101E4690677498B83759FE9A1D001529508F5EB4D46D6';
    const multisigAccount = PublicAccount.createFromPublicKey(multisigAccountPublicKey, NetworkType.MIJIN_TEST);

        // Replace with namespace name and mosaic name
const namespaceName = 'prachakij';
const mosaicName = 'liekcoin';

// 02 - Create Mosaic Definition Transaction
const mosaicDefinitionTransaction = MosaicDefinitionTransaction.create(
    Deadline.create(),
    mosaicName,
    namespaceName,
    MosaicProperties.create({
        supplyMutable: true,
        transferable: true,
        levyMutable: false,
        divisibility: 0,
        duration: UInt64.fromUint(1000)
    }),
    NetworkType.MIJIN_TEST);

// 03 - Create Supply Change Transaction
const mosaicSupplyChangeTransaction = MosaicSupplyChangeTransaction.create(
    Deadline.create(),
    mosaicDefinitionTransaction.mosaicId,
    MosaicSupplyType.Increase,
    UInt64.fromUint(1000000),
    NetworkType.MIJIN_TEST);

// 04 - Wrap both transactions inside an aggregate transaction
const aggregateTransaction = AggregateTransaction.createComplete(
    Deadline.create(),
    [
        mosaicDefinitionTransaction.toAggregate(multisigAccount),
        mosaicSupplyChangeTransaction.toAggregate(multisigAccount)
    ],
    NetworkType.MIJIN_TEST,
    []);

const signedTransaction = cosignatoryAccount.sign(aggregateTransaction);

transactionHttp
    .announce(signedTransaction)
    .subscribe(x=> console.log(x),err => console.error(err));
`

**Comment by jorisadri** [comment]
Please follow this guide to send a transaction from a multisig account:
https://nemtech.github.io/guides/transaction/sending-a-multisig-transaction.html#what-s-next

**Comment by dgarcia360** [comment]
Create namespace:
The transaction is announced with the cosignatory account.The multisig account is not being involved. Wrap the RegisterNamespaceTransaction into an Aggregate transaction by following the tutorial @jorisadri shared.

Create Supply Change Transaction:
The code seems ok. However, if the multisig requires more than one signature, it should be announced as aggregated bonded.

https://nemtech.github.io/guides/transaction/sending-a-multisig-transaction.html#what-s-next

**Comment by ags-21ct** [comment]
thank you 

i'm missing Aggregate transaction

============

const nem2Sdk = require("nem2-sdk");
const operators = require('rxjs/operators');
require('dotenv').load();
    const Address = nem2Sdk.Address,
        Deadline = nem2Sdk.Deadline,
        Account = nem2Sdk.Account,
        UInt64 = nem2Sdk.UInt64,
        NetworkType = nem2Sdk.NetworkType,
        PlainMessage = nem2Sdk.PlainMessage,
        TransferTransaction = nem2Sdk.TransferTransaction,
        Mosaic = nem2Sdk.Mosaic,
        MosaicId = nem2Sdk.MosaicId,
        TransactionHttp = nem2Sdk.TransactionHttp,
        PublicAccount = nem2Sdk.PublicAccount,
        ModifyMultisigAccountTransaction = nem2Sdk.ModifyMultisigAccountTransaction,
        MultisigCosignatoryModification = nem2Sdk.MultisigCosignatoryModification,
        MultisigCosignatoryModificationType = nem2Sdk.MultisigCosignatoryModificationType,
        AccountHttp = nem2Sdk.AccountHttp,
        MosaicDefinitionTransaction = nem2Sdk.MosaicDefinitionTransaction,
        MosaicSupplyChangeTransaction = nem2Sdk.MosaicSupplyChangeTransaction,
        MosaicProperties = nem2Sdk.MosaicProperties,
        MosaicSupplyType = nem2Sdk.MosaicSupplyType,
        XEM = nem2Sdk.XEM,
        AggregateTransaction = nem2Sdk.AggregateTransaction,
        LockFundsTransaction = nem2Sdk.LockFundsTransaction,
        Listener = nem2Sdk.Listener,
        RegisterNamespaceTransaction = nem2Sdk.RegisterNamespaceTransaction,
        filter = operators.filter,
        mergeMap = operators.mergeMap;

        // 01 - Set up
        const transactionHttp = new TransactionHttp( 'http://localhost:3000');

        const cosignatoryPrivateKey = process.env.COSIGNATORY_1_PRIVATE_KEY;
        const cosignatoryAccount = Account.createFromPrivateKey(cosignatoryPrivateKey, NetworkType.MIJIN_TEST);

        const multisigAccountPublicKey = '8AD114F8B5E15D6E3D6101E4690677498B83759FE9A1D001529508F5EB4D46D6';
        const multisigAccount = PublicAccount.createFromPublicKey(multisigAccountPublicKey, NetworkType.MIJIN_TEST);

const namespaceName = "zzz"; //Replace with an unique namespace name

const registerNamespaceTransaction = RegisterNamespaceTransaction.createRootNamespace(
    Deadline.create(),
    namespaceName,
    UInt64.fromUint(1000),
    NetworkType.MIJIN_TEST);

    const aggregateTransaction = AggregateTransaction.createComplete(
        Deadline.create(),
        [registerNamespaceTransaction.toAggregate(multisigAccount),],
        NetworkType.MIJIN_TEST,
        []);

const signedTransaction = cosignatoryAccount.sign(aggregateTransaction);

transactionHttp
    .announce(signedTransaction)
    .subscribe(x => console.log(x), err => console.error(err));
