### ISSUE TITLE
i18n strategies

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-docs#38]
Sphinx enables translating .rst files. By default, the following sections are not possible to be translated:

* ~~Footer~~ (solved)
* Sidebar captions.
* ~~Pages using raw htm~~ (solved)
   * ~~Index: https://nemtech.github.io/ja/index.html~~  (solved)
   * ~~Reference: https://nemtech.github.io/ja/references.html~~  (solved)
* API Endpoints (OpenAPI Specification): https://nemtech.github.io/ja/api/endpoints.html

Each section will require a different translation strategy. The issue has been opened to discuss possible translation approaches.

**Comment by dgarcia360** [comment]
Relevant conversation: https://github.com/sphinx-doc/sphinx/issues/1235

**Comment by kaiyzen** [comment]
not super experienced with translation templating and handling on sphinx so will read up more, but maybe an approach where make/build of the docs doesn't do all in one shot, instead it builds a "target language" and the build/deploy process can set up the directories and whatever is needed

**Comment by dgarcia360** [comment]
@kaiyzen translation is already enabled taking English as the base language.

* Example: https://nemtech.github.io/ja/getting-started/what-is-nem.html
* Guide: https://nemtech.github.io/support/translating-the-documentation.html

The problem right now is that some UI elements are not automatically recognized by the Sphinx translation system.

**Comment by dgarcia360** [comment]
Added ``gettext`` tags to the footer, so now it should be translatable:

https://github.com/nemtech/nem2-docs/commit/e5023b58cd5309e4876a88c7395ff14ef36eaf63#diff-67dcea514bdf82dd986b048ef2e4f679

@44uk Seems the best solution right now, altough is not convenient. Will investigate a little bit further before enabling ``gettext_additional_targets = ['raw']``.

**Comment by dgarcia360** [comment]
Instead of using .rst files for generating landings, Sphinx accepts as well jinja html pages. Will migrate home and references pages to enable translation  👍 

https://ofosos.org/2018/12/28/landing-page-template/

**Comment by dgarcia360** [comment]
Just applied the change proposed to the cow branch. index and reference pages should be translatable after the next release.

**Comment by dgarcia360** [comment]
@44uk Started integrating transifex with sphinx. The command ``make gettext`` seems not to work due to an [issue](https://github.com/sunpy/ablog/issues/30) with ablog. 

Pushed as well a PR fixing the bug, let's wait until sunpy launches the release to continue with transifex integration.
