### ISSUE TITLE
gradle build file name on docs

### ISSUE THREAD

**Issue by denizdurmus** [nemtech/nem2-docs#4]
on https://nemtech.github.io/getting-started/setup-workstation.html#java it says the build file name is gradle.build, while with gradle 3.5 the created file name is build.gradle

not a big issue, but just wanted to make sure if it is a typo or there is a certain version of gradle which would be used while following the tutorial.

**Comment by dgarcia360** [comment]
Thanks for reporting the issue! It was a typo 👍
