### ISSUE TITLE
Server Reference

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-docs#48]
NEM developer center will have a section describing how the Catapult-server is organized and guides to launch private networks and public nodes.

## Deliverables

**Server Reference**
* Overview
* [Installation](https://github.com/nemtech/catapult-server/blob/master/BUILDING.md)
* Guides

**Comment by daoka** [comment]
Thank you for reference !!

Yes, I generate with doxygen.

This is a doxygen config file.
https://gist.github.com/daoka/502ffa62f77cfd490e267c1fb31c2d61#file-doxyfile

Doxygen generates about 10000 files on the same directory.
So, document can't upload to Github XD

**Comment by dgarcia360** [comment]
Added auto-generated [configuration parameters](https://gist.github.com/dgarcia360/4e51a8c979373ada910fc26483635657)

**Comment by dgarcia360** [comment]
Work in progress: [Catapult-Server Reference](https://github.com/nemtech/nem2-docs/tree/48-catapult-server-reference)
