### ISSUE TITLE
Error Provide a valid NEM2 Node URL. Example: http://localhost:3000

### ISSUE THREAD

**Issue by olishiz** [nemtech/nem2-docs#5]
Hello there, I'm having issue with this NEM2 Node URL.

I am unable to create an account because of this problem

any idea on how to fix this?

**Comment by aleixmorgadas** [comment]
The URL is provided when you receive the Catapult Developer Preview invitation.

The webpage page to apply is [mijin.io/en/catapult](http://mijin.io/en/catapult)
