### ISSUE TITLE
[Guide] Set account filters

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-docs#58]
Create a step-by-step guide explaining how an account can set [account-filters](https://nemtech.github.io/concepts/account-filter.html).

The guide will use the Typescript SDK. The target audience is developers who want to integrate this functionality into their app.

## Deliverables

* Guide
* Code example

## Dependencies

-  ~~https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/50~~ (solved)

## Resources

* [How to write a guide](https://nemtech.github.io/guidelines/writing-a-guide.html)
* [Account Filters](https://nemtech.github.io/concepts/account-filter.html)
* [AccountPropertyTransaction class](https://nemtech.github.io/nem2-sdk-typescript-javascript/classes/_model_transaction_accountpropertytransaction_.accountpropertytransaction.html)

**Comment by Boohi** [comment]
I will start working on this

**Comment by dgarcia360** [comment]
@Boohi Updated the description with some links. 

You will see that the SDK function to work with account filters is not implemented. The guide can still be written, reviewing if the code proposed works or needs some minor changes.

**Comment by rg911** [comment]
@Boohi sorry to reply late this is done in #50

**Comment by dgarcia360** [comment]
@rg911 I think there are no duplicated efforts, @Boohi is planning to create a step by step guide explaining how to use the SDK.

Example of usage guide: https://nemtech.github.io/concepts/cross-chain-swaps.html

**Comment by dgarcia360** [comment]
SDK updated https://github.com/nemtech/nem2-sdk-typescript-javascript/releases/tag/v0.10.3-4

**Comment by dgarcia360** [comment]
@Boohi I'll take this issue during the following week. If you have something started, please do not hesitate to upload a PR.

**Comment by dgarcia360** [comment]
Working on this.
