### ISSUE TITLE
[Guide] Activate delegated harvesting

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-docs#63]
Create a step-by-step guide to activate/deactivate remote  [harvesting](https://nemtech.github.io/concepts/harvesting.html).

The guide will use the Typescript SDK to activate the delegate harvesting. The target audience is developers who want to integrate this functionality into their client app or wallet.

## Deliverables

* Guide
* Code example

## Dependencies

* catapult-server should support #161 
* REST & TS SDK should support #161

## Resources

* [How to write a guide](https://nemtech.github.io/guidelines/writing-a-guide.html)
* [Harvesting docs](https://nemtech.github.io/concepts/harvesting.html)
* [AccountLinkTransaction class](https://nemtech.github.io/nem2-sdk-typescript-javascript/classes/_model_transaction_accountlinktransaction_.accountlinktransaction.html)

**Comment by kyleqchain** [comment]
I can take this one

**Comment by dgarcia360** [comment]
@kyleqchain Updated the description with some links. 

You will see that the SDK function to enable delegated harvesting is not implemented yet. The guide can still be written, reviewing if the code proposed works or needs some minor changes.

**Comment by dgarcia360** [comment]
@kyleqchain The latest SDK version enables to send AccountLinkTransactions.
