### ISSUE TITLE
[Concept] Light clients + Merkle Trees

### ISSUE THREAD

**Issue by CrackTheCode016** [nemtech/nem2-docs#65]
Light node post below:
https://forum.nem.io/t/catapult-101-light-nodes/21684

**Comment by dgarcia360** [comment]
Thanks @CrackTheCode016 for your contribution! I would keep light nodes outside the docs scope right now, but definitely a good reference for the future.

Right now "Light Clients" could go inside "Protocol/Block" or "Protocol/Node". If we explain how Merkle trees work, we can think about creating a specific section. 

Attached the tag "good first issue", in case someone wants to include more content and do a PR.

**Comment by CrackTheCode016** [comment]
Sounds good @dgarcia360!  When I find some time, I will add more a detailed explanation regarding Merkle trees and how they tie into light clients when I find the time in the next week.  I anticipate this would be appropriate in the `cow` branch, correct?

**Comment by dgarcia360** [comment]
Information about state roots: https://twitter.com/NCOSIGIMCITYNRE/status/1091312236742803456

**Comment by dgarcia360** [comment]
Missing an endpoint to validate if a state hash belongs to a certain block.
