### ISSUE TITLE
API behavior is different from nem2-doc

### ISSUE THREAD

**Issue by arara-mizoguchi** [nemtech/nem2-docs#66]
API : `http://localhost:3000/blocks/{height}/limit/{limit}`
https://nemtech.github.io/api/endpoints.html#operation/getBlocksByHeightWithLimit

**Two different point about " {limit} ".**
1. Although " limit >= 0 " is described, it operates as ` limit = 25` except when `limit = 25, 50, 75, 100`.
2. There is description " The number of following blocks to be returned. ".
It can be read that blocks with height `height ~ (height + limit -1)` can be obtained.
However, in fact we get the block whose height is `(height - limit + 1) ~ height`.

**environment**
catapult-service-bootstrap 77e6cf38a7845194aa2ce72f4ed4d87e5ab791e3

I don't know whether this is the ultimate specification of the API, but it is a fact that the behavior of nem2-doc and API is different.

**Comment by dgarcia360** [comment]
Thanks for noticing @arara-mizoguchi! It has been solved in a new branch, and will be merged into master during the next release.
