### ISSUE TITLE
[Concept] Block difficulty

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-docs#71]
Add a complete description for the block difficulty.

* https://nemtech.github.io/concepts/block.html#blockheader
* https://nem.io/wp-content/themes/nem/files/NEM_techRef.pdf

**Comment by kyleqchain** [comment]
I'll work on this, David

**Comment by dgarcia360** [comment]
Thanks, @kyleqchain! If you have any doubts do not hesitate to add them to this issue.

**Comment by kyleqchain** [comment]
@dgarcia360 Did you receive my pull request on this issue?
