### ISSUE TITLE
Update Namespaces documentation

### ISSUE THREAD

**Issue by jabo38** [nemtech/nem2-docs#76]
There is an examples section on https://nemtech.github.io/concepts/namespace.html

Even though I got the general point and it made sense. I want to offer an improved example to make things more clear for the reader. 

Scenario 1:
A customer buys a ticket for an event, a ticket sales company sends a ticket to the customer account.

Identifying the Sender
The seller company has bought the namespace "ticketsales" and assigned the namespace “ticketsales” as an alias to its main account. Customers can quickly recognize incoming transactions from the vendor account.

Indentifying Mosaic
The same company sells tickets for an events organized in different venues. The company registers a non-transferable mosaic for each function. A series of subdomains are added on top of the root domain of "ticketsales". The root plus subdomains are "ticketsales.eventname.ticket". The distributor assigns  "ticketsales.eventname.ticket" as an alias to their mosaic. 

A customer's address can now receive 1 "ticketsales.eventname.ticket" from the account "ticketsales" instead of 1 0xE4EEB491 from SCVG35-ZSPMYP-L2POZQ-JGSVEG-RYOJ3V-BNIU3U-N2E6.

Identifying the Receiver
Furthermore, if Alice is the customer of the ticket and she has registered the namespace "Alice" and assigned it to her account as an alias. Then the transaction on the blockchain can read Alice receives 1 "ticketsales.eventname.ticket" from the account "ticketsales" instead of SAV3MF-KO7RPO-FBBGMS-FDQXJ4-3AF3NO-OFWTCL-PLSA receives 1 0xE4EEB491 from SCVG35-ZSPMYP-L2POZQ-JGSVEG-RYOJ3V-BNIU3U-N2E6.

**Comment by dgarcia360** [comment]
Thanks @jabo38 for the suggestion! Next release will apply some of the feedback and a graphic to make it even clearer.

**Comment by dgarcia360** [comment]
Namespace docs [updated](https://nemtech.github.io/concepts/namespace.html)

**Comment by ivyfung1** [comment]
I can work on this too.

**Comment by dgarcia360** [comment]
Hi @ivyfung1, this issue was solved already. What do you want to add?
