### ISSUE TITLE
confusing comments in src\model\account\Address.d.ts

### ISSUE THREAD

**Issue by cfcodefans** [nemtech/nem2-docs#8]
/**
     * Create from private key
     * @param publicKey - The account **private** key.
     * @param networkType - The NEM network type.
     * @returns {Address}
     */
    static createFromPublicKey(publicKey: string, networkType: NetworkType): Address;

Create from **private** key
@param **publicKey** - The account **private** key.

so is it the public key or private key?

**Comment by dgarcia360** [comment]
Thanks for reporting the bug. It should be:

 * @param **publicKey** - The account **public** key.

Could you please report it under nem2-sdk-typescript-javascript repository? [nem2-sdk-typescript-javascript](https://github.com/nemtech/nem2-sdk-typescript-javascript/issues)

**Related file:** https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/account/Address.ts
