### ISSUE TITLE
Layout update

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-docs#81]
Based on feedback received and research, we'll apply the following changes to the NEM Developer Center.

## Refactor sidebar

*Problem*: Adding new references (wallet, tools, catapult-server), will make difficult the sidebar navigation.
*Solution*: Wrap API, SDK, Client, Libraries and prototyping tool under a "Reference" tab. 

## Add a secondary sidebar

*Problem*: It's difficult to navigate through documents, as there is no table of contents.
*Solution*: At the right part of the screen, we'll have a new sidebar containing the table of contents of the document. 

The content will be more centered, enhancing the readability. Furthermore, it will allow merging some documents, for example, Prototyping Tool Overview, Configuration, and Examples can be merged into a single file.

Submitted a [PR](https://github.com/sphinx-contrib/fulltoc/issues/2) to enable this feature.

## Improve top navbar
*Problem*: The language selector is hidden (footer), and the search page is not good enough.
*Solution*: The top bar will include [algolia search](https://community.algolia.com/docsearch/) if we get accepted to the program, and the language selector will be placed in the top sidebar.

## Update Footer
The footer will be edited to follow the proposed structure, giving more importance to the community.

* Documentation
* References
* Community

**Comment by dgarcia360** [comment]
![image](https://user-images.githubusercontent.com/9107969/53162492-0aa5a200-35c4-11e9-9a1b-c9c8ea83143c.png)

**Comment by jontey** [comment]
For the footer, what is the main difference between documentation and references?

**Comment by dgarcia360** [comment]
![image](https://user-images.githubusercontent.com/9107969/53230769-55382480-367f-11e9-94a6-840d5cf83c81.png)

**Comment by jontey** [comment]
I see that References is shown twice. Is the one on the left column redundant?

**Comment by dgarcia360** [comment]
@jontey We could delete References from the left sidebar, it's redundant. Thanks for the feedback!

**Comment by dgarcia360** [comment]
We have been accepted to Algolia's docsearch program:

https://github.com/algolia/docsearch-configs/blob/master/configs/nemtech.json

**Comment by dgarcia360** [comment]
PR pending to be merged https://github.com/nemtech/nem2-docs/pull/89
