### ISSUE TITLE
New landing page proposal

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-docs#91]
An issue to discuss a possible redesign of the developer's center landing page. We'll start gathering requirements in this issue.

Jeff's comment in Slack:

> *The Landing Page*
The goal is to keep this as beautiful as possible and highlight links, boxes, shortcuts, and provide shortcuts and direct access to the most commonly used docs.
This is done by combining the current landing page which is a great start and References page which is styled similarly.
We can add another section for guides and/or education or other important link categories in the future to compliment the content already there.

**Comment by dgarcia360** [comment]
Here there is the new landing proposed and some navigation changes that will be published along with dragon-01 docs. Feedback is welcomed and appreciated!

![image](https://user-images.githubusercontent.com/9107969/56981379-acbea900-6b76-11e9-909d-b828f1a47335.png)
![Uploading image.png…]()

**Comment by jabo38** [comment]
I think these are great suggestions and will make it easier for people to quickly get to the content they need while also understanding the overall content available at a first glance.
