### ISSUE TITLE
MosaicProperty property 'mosaicId' should be 'value'

### ISSUE THREAD

**Issue by fullcircle23** [nemtech/nem2-docs#95]
The [mosaic_definition.cats schema](https://github.com/nemtech/catbuffer/blob/master/schemas/mosaic/mosaic_definition.cats) in Catbuffer repo defines MosaicProperty as composed of an **id** and a **_value_** but [nem2-docs](https://github.com/nemtech/nem2-docs/blob/master/source/concepts/mosaic.rst#mosaicproperty) is showing the properties of MosaicProperty to be **id** and **_mosaicId_** (instead of value). Please correct it or clarify. Thanks.

**Comment by dgarcia360** [comment]
Thanks for reporting! It has been corrected and will be visible in the next release.
